### PR TITLE
Correct un-secure image issue #WPT-47

### PR DESCRIPTION
**Pull request by dcfreema**
Correct un-secure image issue #WPT-47

### CODE REVIEW

**Comment by timlevett** [comment]
Wouldn't it be easier to just update the parsing service specifically for yahoo?

https://github.com/Jasig/WeatherPortlet/blob/d3c9c6ad14acc41aca7ad39f251c8c02ed2add31/src/main/resources/org/jasig/portlet/weather/dao/yahoo/YahooWeatherParsingServiceImpl.groovy#L42

**Comment by jameswennmacher** [comment]
@timlevett Great feedback Tim.  Good attention to detail.

**Comment by dcfreema** [comment]
@timlevett Thanks for the advice, I will submit a new pull request.

**Comment by timlevett** [comment]
Closing in favor of #16

**Pull request closed without merging**
